---
title: "Test"
author: "Avinash"
date: '2018-01-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(maps)
library(gapminder)
library(ggmap)
library(knitr)
theme_set(theme_bw())

```

```{r}
data <- read_csv("../data/crime.csv")

data$Country %>% unique()

kable(data)

```
```{r}



ggplot() +
    geom_polygon(data = map_data("usa"),
        aes(x = long, y = lat, group = group), colour = "grey", fill = "white") +
    geom_point(data = rbind(maps::us.cities),
        aes(x = long, y = lat)) +
    coord_quickmap()

states <- map_data("state")

maps::

city <- map_data("city")


state_colors <- sample(x = country_colors, size = 49)

new <- states %>% group_by(region) %>% summarise() %>% as.list()

names(new) <- NULL

new <- new[[1]]

names(state_colors) <- new

state_colors[c(1,2,16,25)] <- c(country_colors['Australia'], country_colors['New Zealand'])

ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, group = group), color = "black", fill = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE) + scale_fill_manual(values = state_colors)




ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "black") + 
  coord_fixed(1.3) +
  guides(fill=FALSE) + scale_fill_manual(values = as.matrix(read.table("../doc/color.txt"))) + theme_void()

write.table(x = as.data.frame(state_colors), file = "../doc/color.txt")



names(state_colors)



subset(crime, state == "texas") %>% ggplot(aes(year, violent_crime)) + geom_point(aes(color = fct_reorder(dep_name, total_pop, .desc = TRUE))) + geom_path(aes(group = dep_name, color = dep_name)) + scale_color_discrete("Cities") + labs(title = "Population in Texas", x = "Year", y = "Total Population") +
  theme(plot.title = element_text(hjust = 0.5, size = 17, face = "bold"), axis.title = element_text(size = 14))


df %>%	ggplot() + geom_polygon(aes(x = long, y = lat, group = group, fill = total_pop)) +
  scale_fill_continuous("Total Population", low = "springgreen4", high = "black") + theme_void()

ncol(data)

```

```{r}
names(data)

crime %>% fct_reorder(department_name, as.factor(violent_crime), .desc = TRUE)

fct_reorder(data,ORI, violent_crime)


data <- as.tibble(data)

?fct_reorder

data

data <- data %>% mutate(cities = as.factor(department_name))

data

crime
```



```{r}

state_names <- crime %>% group_by(department_name) %>% summarise() %>% rowwise() %>%  mutate(state = geocode(department_name, output = "all")$results[[1]]$address_components[[3]]$long_name)

#https://stackoverflow.com/questions/20937682/r-trying-to-find-latitude-longitude-data-for-cities-in-europe-and-getting-geocod

crime %>% group_by(department_name) %>% summarise()

crime <- data[,1:15]

crime <- left_join(crime, state_names)

state_names[c(6,7,19,30,35,38,40,43,53,62,63,67),2] = c("Maryland", "Maryland", "virginia", "california", "florida", "Maryland", "new york", "new york", "Maryland", "missouri", "new york", "virginia")

state_names[c(10,36, 41),2] <- c("North Carolina" ,"Wisconsin", "Oklahoma")

state_names %>% group_by(state) %>% summarise(count = n()) %>% arrange(count)

crime <- crime %>% mutate(region = tolower(state))

write.csv(crime, "../results/crime_processed.csv")

df <- left_join(states, subset(crime, year == 1986) , by = "region")

crime <- crime %>% separate(department_name, into = c("dep_name", "extra"), sep = ",")

```

